### PR TITLE
Structure for Citing the tools

### PR DESCRIPTION
**Pull request by stain**
Added Work in Progress from hackathon 2021-03-22

From
https://codimd.carpentries.org/vqiilE7ESsy4x1N9KM6bxg?edit#

Credits: @stain @Pfern Chara

### CODE REVIEW

**Comment by stain** [comment]
Need some help with marking up TODOs etc.

**Comment by tobyhodges** [comment]
This looks like a very good start. One thing I noticed is that the content goes into a lot more practical detail, about _how_ to write CWL to cite tools used in a workflow. I don't think this is fully captured in the objective/outcome written at the start of the page:

> By the end of this epsiode, learners should be able to explain the importance of correctly citing research software.

Would you like to define one or two more objectives/outcomes for the section? Or shall I add a TODO for this?

**Comment by stain** [comment]
Would need a TODO for that.. it's a bit broader now than as this episode started. Also links to #34 for intro video.

**Review by tobyhodges — APPROVED** [review]
Some more work to be done on this episode but I will merge this for now.

**Pull request merged**
