### PR TITLE
use a smaller dataset

### LINKED ISSUE #51: Shrink dataset
400MiB is doable, but smaller is better

([via](https://github.com/carpentries-incubator/cwl-novice-tutorial/pull/50#discussion_r754368816))

### PR DESCRIPTION
**Pull request by mr-c**
Fixes #51 
Builds upon @douglowe 's work in https://github.com/douglowe/cwl-tutorial-material-prototype

### CODE REVIEW

**Comment by mr-c** [comment]
Ah, this means we will have to re-make the graphs that @aluesink made :-/

**Comment by douglowe** [comment]
I'm trying the new setup out now.

The final build step in the setup page is still taking a long time (8 minutes, and counting). 3Gb is getting closer to a reasonable size for direct download - do you have a download link for this anywhere?

Otherwise, it might be we have to specify that setup is done before the teaching session - perhaps as an organised 1 hour setup session a day or two beforehand?

**Comment by mr-c** [comment]
> The final build step in the setup page is still taking a long time (8 minutes, and counting)

To speed it up, I personally edited the CWL description to specify `coresMin: 4` (the number of real CPUs in my laptop) under `ResourceRequirement`

>  3Gb is getting closer to a reasonable size for direct download - do you have a download link for this anywhere?

I can upload this somewhere, yes. Do you have a recommend location?

**Comment by mr-c** [comment]
> Otherwise, it might be we have to specify that setup is done before the teaching session - perhaps as an organised 1 hour setup session a day or two beforehand?

Could be; I might merge this now as the VU Amsterdam class is supposed to start in a number of minutes

**Comment by douglowe** [comment]
> 



> > The final build step in the setup page is still taking a long time (8 minutes, and counting)
> 
> To speed it up, I personally edited the CWL description to specify `coresMin: 4` (the number of real CPUs in my laptop) under `ResourceRequirement`
> 
Ahh, my laptop has only 2 cores - I could try specifying 2 cores, that might help a little (though I'm at 25 minutes and still counting). Also, I've limited docker to 6Gb RAM, which might be slowing things down too.

> > 3Gb is getting closer to a reasonable size for direct download - do you have a download link for this anywhere?
> 
> I can upload this somewhere, yes. Do you have a recommend location?

Perhaps upload to Zenodo? That might be easiest (and free). Or UoM does have a deal with figshare for longterm storage - so I could upload there?

**Comment by douglowe** [comment]
> > Otherwise, it might be we have to specify that setup is done before the teaching session - perhaps as an organised 1 hour setup session a day or two beforehand?
> 
> Could be; I might merge this now as the VU Amsterdam class is supposed to start in a number of minutes

Yes - good plan.

Good luck with the class!

**Review by douglowe — APPROVED** [review]
The changes look reasonable to me - let's try these, and sort out build times later.

**Pull request merged**
